# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.13"
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  CIBW_BUILD: cp36-* cp37-* cp38-* cp35-*
  CIBW_TEST_COMMAND: python {project}/tests/test_base.py
  MACOSX_DEPLOYMENT_TARGET: "10.10"
  CIBW_BEFORE_BUILD: pip install numpy cython

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Use Python 3.6'

- script: |
    python -m pip install --upgrade pip
    python -m pip install git+https://github.com/Czaki/cibuildwheel
  displayName: 'Install dependencies'

- script: |
    python -m cibuildwheel
  displayName: 'cibuildwheel'

- bash: | 
    if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
     python -m pip install numpy cython; 
     python setup.py sdist -d wheelhouse; 
    fi
  displayName: sdist

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: wheelhouse
    artifactName: wheels
